nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs

packageExtensions:
  '@typescript-eslint/utils@*':
    dependencies:
      typescript: '*'
  'eslint-config-react-app@*':
    dependencies:
      '@babel/plugin-syntax-flow': '^7.14.5'
      '@babel/plugin-transform-react-jsx': '^7.14.9'
